-- =========================
-- DROP TABLES IN REVERSE ORDER OF DEPENDENCY
-- =========================
DROP TABLE IF EXISTS Rating;
DROP TABLE IF EXISTS Contains;
DROP TABLE IF EXISTS Cart;
DROP TABLE IF EXISTS Restaurant_Keyword;
DROP TABLE IF EXISTS Keyword;
DROP TABLE IF EXISTS Discount;
DROP TABLE IF EXISTS Menu_Item;
DROP TABLE IF EXISTS Restaurant;
DROP TABLE IF EXISTS Phone_Number;
DROP TABLE IF EXISTS Address;
DROP TABLE IF EXISTS Restaurant_Manager;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS User;
